services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  spark:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars/*:/opt/bitnami/spark/drivers/*
      - SPARK_DRIVER_CLASSPATH=/opt/bitnami/spark/drivers/postgresql-42.6.0.jar
      - SPARK_EXECUTOR_CLASSPATH=/opt/bitnami/spark/drivers/postgresql-42.6.0.jar
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./drivers:/opt/bitnami/spark/drivers
    networks:
      - bitsight-network

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: bitsight-spark-worker-1
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars/*:/opt/bitnami/spark/drivers/*
      - SPARK_DRIVER_CLASSPATH=/opt/bitnami/spark/drivers/postgresql-42.6.0.jar
      - SPARK_EXECUTOR_CLASSPATH=/opt/bitnami/spark/drivers/postgresql-42.6.0.jar
    volumes:
      - ./drivers:/opt/bitnami/spark/drivers
    networks:
      - bitsight-network

  postgres:
    image: postgres:15-alpine
    container_name: bitsight-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bitsight
      POSTGRES_PASSWORD: poorna
      POSTGRES_USER: poorna
    networks:
      - bitsight-network

networks:
  bitsight-network:
    driver: bridge

volumes:
  postgres_data:
